name: project3
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip==22.3.1
  - scikit-learn==1.1.3 
  - pandas==1.5.2
  - numpy==1.23.5
  - pytest==7.2.0
  - jupyter==1.0.0
  - jupyterlab==3.5.1
  - fastapi==0.88.0 
  - uvicorn==0.20.0
  - flake8==5.0.4

